FROM python:3.11-slim

WORKDIR /app

RUN pip install fastapi uvicorn pydantic --no-cache-dir

COPY api/main_kube.py api/main_kube.py

EXPOSE 8000

CMD ["uvicorn", "api.main_kube:app", "--host", "0.0.0.0", "--port", "8000"]